# Generated by Django 4.2 on 2024-11-11 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_available_courses_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_courses',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutoraddcourse', to=settings.AUTH_USER_MODEL),
        ),
    ]
