# Generated by Django 4.2 on 2024-11-11 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_available_courses_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='title',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseattendance', to='Users.available_courses'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='Timeanddate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time & date joined'),
        ),
    ]
