# Generated by Django 4.2 on 2024-11-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_studentattendance_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='title',
            field=models.CharField(default='All Students Attendance', max_length=50, null=True),
        ),
    ]
