# Generated by Django 4.2 on 2024-11-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_studentattendance_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='title',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='course_attendance',
            field=models.CharField(max_length=50, null=True, verbose_name='Attendance Course'),
        ),
    ]
