# Generated by Django 4.2 on 2024-11-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_remove_studentattendance_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattendance',
            old_name='course',
            new_name='course_code',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='course_attendance',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='course_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Attendance Course Name'),
        ),
    ]
