# Generated by Django 4.2 on 2024-11-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_rename_course_studentattendance_course_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='available_courses',
            old_name='tutor',
            new_name='author',
        ),
    ]
