# Generated by Django 4.2 on 2024-11-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_rename_tutor_available_courses_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='Timeanddate',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='entry_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(choices=[('P', 'PRESENT'), ('A', 'ABSENT')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_tutor',
            field=models.BooleanField(default=True, null=True, verbose_name='Tutor Status'),
        ),
    ]
