# Generated by Django 4.2 on 2024-11-12 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_remove_studentattendance_timeanddate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentattendance',
        ),
    ]
