# Generated by Django 4.2 on 2024-11-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_studentattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(choices=[('P', 'PRESENT'), ('A', 'ABSENT')], default='PRESENT', max_length=10),
        ),
    ]
