# Generated by Django 5.1.3 on 2024-11-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattendance',
            old_name='course_code',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='course_name',
        ),
    ]
