# Generated by Django 5.1.3 on 2024-11-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_rename_course_code_studentattendance_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattendance',
            old_name='course',
            new_name='course_code',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='course_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Attendance Course Name'),
        ),
    ]
