# Generated by Django 5.1.3 on 2024-11-18 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0018_studentatten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentatten',
            name='course_name',
        ),
    ]
