# Generated by Django 5.1.3 on 2024-11-18 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_studentatten_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='sturegistercourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True, unique=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sturegcoursename', to='Users.available_courses')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseregname', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
