# Generated by Django 5.1.3 on 2024-11-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_sturegistercourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sturegistercourse',
            name='username',
        ),
        migrations.AddField(
            model_name='sturegistercourse',
            name='FirstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sturegistercourse',
            name='LastName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
