# Generated by Django 5.1.3 on 2024-11-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0022_remove_sturegistercourse_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='anouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tutor', models.CharField(max_length=20, null=True)),
                ('title', models.CharField(max_length=255, null=True, unique=True)),
                ('content', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sturegistercourse',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
