# Generated by Django 5.1.3 on 2024-11-19 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0023_anouncement_sturegistercourse_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tutor', models.CharField(max_length=20, null=True)),
                ('title', models.CharField(max_length=255, null=True, unique=True)),
                ('content', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createassginmentcourse', to='Users.available_courses')),
            ],
        ),
    ]
