# Generated by Django 4.2 on 2024-11-21 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0026_delete_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursetimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetablecourse', to='Users.available_courses')),
            ],
        ),
    ]
