# Generated by Django 4.2 on 2024-11-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0027_coursetimetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetimetable',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
