# Generated by Django 4.2 on 2024-11-21 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0029_coursemodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetimetable',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetablecourse', to='Users.coursemodule'),
        ),
    ]
