# Generated by Django 4.2 on 2024-11-21 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0030_alter_coursetimetable_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentatten',
            name='course_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseattendance', to='Users.coursemodule'),
        ),
    ]
