# Generated by Django 4.2 on 2024-11-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0031_alter_studentatten_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentatten',
            name='student_name',
        ),
    ]
