# Generated by Django 4.2 on 2024-11-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0033_examtimetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtimetable',
            name='link',
            field=models.CharField(default='https://wanjos.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='examtimetable',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
