# Generated by Django 4.2 on 2024-11-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0035_passwordreset_alter_examtimetable_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='passwordreset',
            name='email',
        ),
        migrations.RemoveField(
            model_name='passwordreset',
            name='token',
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
