# Generated by Django 4.2 on 2024-11-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0036_remove_passwordreset_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
